project:
  type: website

website:
  page-navigation: true
  title: "Clinical Reporting with {gtsummary}"
  description: "Homepage for the R/Medicine 2022 Workshop"
  site-url: "https://www.danieldsjoberg.com/R-Med-gtsummary-workshop/"
  
  repo-url: https://github.com/ddsjoberg/R-Med-gtsummary-workshop
  repo-actions: [edit, issue]

  opengraph: true
  twitter-card:
    creator: "@statistishdan"
    # image: "/images/twitter-card.png"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2022, Daniel D. Sjoberg"
    background: "#2e3846"

  sidebar:
    background: "#2e3846"
    logo: "images/gtsummary-logo.jpg"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/ddsjoberg/R-Med-gtsummary-workshop
        text: GitHub
    style: docked
    contents:
     - href: index.qmd
       text: Home

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    toc: true
    code-copy: true
    code-overflow: scroll
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y

editor: visual

