project:
  type: website
  render:
    - "*.qmd"
    - "!exercises/exercises.Rmd"
    
website:
  page-navigation: true
  title: "Clinical Reporting with {gtsummary}"
  description: "Homepage for the R/Medicine 2022 Workshop"
  site-url: "https://www.danieldsjoberg.com/clinical-reporting-gtsummary-rmed/"
  favicon: "images/trans - gt.png"
  
  repo-url: https://github.com/ddsjoberg/clinical-reporting-gtsummary-rmed
  repo-actions: [edit, issue]

  opengraph: true
  twitter-card:
    creator: "@statistishdan"
    image: "/images/two-hex-logo.png"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/). Inspired by [@minebocek](https://twitter.com/minebocek)"
    right: "&copy; Copyright 2022, Daniel D. Sjoberg"
    background: "#708090"

  sidebar:
    background: "#708090"
    logo: "images/trans - gt.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/ddsjoberg/clinical-reporting-gtsummary-rmed
        text: GitHub
    style: docked
    contents:
     - href: index.qmd
       text: Home
     - href: material.qmd
     - href: license.qmd

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: scroll
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y

editor: visual

