on:
  push:
    branches: [main, master]
    tags: ['*']

name: deploy

env:
  RENV_PATHS_ROOT: ~/.local/share/renv
  
jobs:
  quarto-publish:
    name: Publish with Quarto
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
            
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
          
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          
      - name: Zip Exercises
        shell: Rscript {0}
        run: |
          zip::zip(zipfile = "exercises/exercises.zip", files = c("exercises/exercises.Rmd", "clinical-reporting-gtsummary-rmed.Rproj"), root = here::here(), recurse = FALSE, mode = "cherry-pick")
          
      - name: Commit files
        run: |
          git config --global user.email "ghau@example.com"
          git config --global user.name "GitHub Actions User"
          git add exercises/exercises.zip
          git commit -am "adding exercises.zip"
          git push -f
          
          