on:
  push:
    branches: [main, master]
    tags: ['*']

name: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: peaceiris/actions-gh-pages@v3
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./_site"
